---
# This playbook deploys the whole application stack in this site.

- name: Central
  hosts: central
  remote_user: centos

  roles:
    - common
    - central

- name: Poller
  hosts: poller
  remote_user: centos

  roles:
    - common
    - poller

- name: Db
  hosts: dbserver
  remote_user: centos

  roles:
    - common
    - db

- name: Common
  hosts: common
  remote_user: centos

  roles:
    - common
